<a href="https://colab.research.google.com/github/Madhan-analyst/Madhan-analyst/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('numpy-array-operations')
jovian.set_colab_id('1VEmfvBjfofaGk_mGDxVhS99a0T5VqQLg')

     |████████████████████████████████| 68 kB 2.9 MB/s 


> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Simple Yet interesting Numpy Functions that a Datascience Beginner should know! :)


So, in this assignment, I am going to discuss about the 5 statistical numpy functions in Python.

- np.char.find
- np.nanmean
- np.extract
- np.trim_zeros
- np.unique


In [ ]:
!pip install jovian --upgrade -q

In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

## List of functions explained 
- function1 = np.char.find()
- function2 = np.nanmean()
- function3 = np.extract()
- function4 = np.trim_zeros()
- function5 = np.unique()

## **1. np.char.find**

This function helps us to find a ***sub string*** in an **array of strings**. It returns the lowest index of that sub string in the string array. If the sub string is **not present**, then it returns the last index of the string i.e., **-1**.

In [ ]:
# Example 1 - working (change this)
arr1 = np.array(["madhan","jotha dhapan","geetha"])

np.char.find(arr1,"mad")

array([ 0, -1, -1])

The sub string "mad" is present only in the first element of the array. So,the function returns that it presents in ***0th index of the  first string*** and returns -1 implying that doesn't present in those strings. 

In [ ]:
# Example 2 - working
np.char.find(arr1,"dha",start=4)

array([-1,  6, -1])

Here, The sub string "dha" is present in both first and second elements of the array. But,the function returns that it presents only in the **6th index of second string**  since the start index we gave is 6. That's why it showing that the first string is not having "mad".

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.array([1, 2 ,3, 4])

np.char.find( arr2, 2)

TypeError: ignored

Here, it's showing an error because we passed the numerical array as an argument instead of a string array. It can be solved by converting the numerical values as a string in the array. i.e.,

In [ ]:
arr2 = np.array(["1", "2" , "3", "4"])

np.char.find( arr2, "2")

array([-1,  0, -1, -1])

This function helps us to find a particular string in the String array of large datasets.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

## **2. np.nanmean**

This function can be used to calculate the ***mean of array ignoring the NaN*** value. It's very much useful if our array contains Nan values and we can easily find out the mean without the effect of Nan values. 

In [ ]:
# Example 1 - working
arr3 = [11,2,np.nan,5,8,10,np.nan] 

np.nanmean(arr3)

7.2

It calculates the mean value of 11,2,5,8 and 10 as 7.2 by ignoring the Nan values.

In [ ]:
# Example 2 - working
arr4 = np.array([[2,np.nan,4,6,np.nan],
        [3,np.nan,5,7,9]])

np.nanmean(arr4,axis=1)

array([4., 6.])

Here, we have added an argument axis = 1, so it calculates the mean values of the second dimension values.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr5 = [12, 15, 18, nan, 21, 17]

np.nanmean(arr5)

NameError: ignored

Here, the ***nan*** value is treated as a *variable*. The function only ignores the nan values if it's in the form of ***`np.nan`***, otherwise it throws an error. It can be solved by

In [ ]:
arr5 = [12, 15, 18, np.nan, 21, 17]

np.nanmean(arr5)

16.6

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

## **3. np.extract**

The numpy.extract() function returns **elements** of input_array if they satisfy some **specified condition**.

In [ ]:
# Example 1 - working
arr6 = np.array(range(100,200,3))

np.extract((arr6%5)>3,arr6)

array([109, 124, 139, 154, 169, 184, 199])

Here, it returns the array elements which satisfy the condition. 

In [ ]:
# Example 2 - working
sales = np.random.randint(1000,10000,size=110)

np.extract(sales>8000, sales)

array([8374, 9369, 9722, 8744, 9205, 8046, 9953, 9602, 8359, 9194, 8292,
       8675, 9685, 9797, 9137, 8212, 8763, 9079, 9954, 8453, 9001, 9306,
       9315, 9633, 8292, 8120, 9962, 8379, 8025, 9295])

Here, it returns only the sales which are greater than 8000.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr7 = [2, 7, 9, 17]

np.extract(arr7 >10, arr7)

TypeError: ignored

This function **does not accept** the **list** as an argument like the previous functions. It accepts only the array. That's why it's showing the error. It can be treated as

In [ ]:
arr7 = np.array([2, 7, 9, 17])

np.extract(arr7 >10, arr7)

array([17])

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

## **4. np.trim_zeros**

numpy.trim_zeros function is used to trim the ***leading and/or trailing zeros*** from a 1-D array.

In [ ]:
# Example 1 - working
arr8 = np.array([0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0])

np.trim_zeros(arr8)

array([ 1,  5,  7,  0,  6,  2,  9,  0, 10])

The function removes the leading and trailing zeros in the array.

In [ ]:
# Example 2 - working

np.trim_zeros(arr8, trim ="f")

array([ 1,  5,  7,  0,  6,  2,  9,  0, 10,  0,  0])

Here, the function removes only the leading zeros. It's because of the argument that we gave ***trim='f'*** which means remove zeros only in the **front**.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr9 = np.array([[0,0,0,2,3,5],
                 [7,8,9,0,0,0]])

np.trim_zeros(arr9,trim="b")

ValueError: ignored

Here, we passed a 2D array to the function. That's why the error occured. The function only accepts 1D array or a sequence. Thus, it can be solved by

In [ ]:
arr9 = arr9.reshape(12)

np.trim_zeros(arr9,trim="b")

array([0, 0, 0, 2, 3, 5, 7, 8, 9])

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

## **5. np.unique**

This function returns the ***unique*** values in a sorted manner from an array.

In [ ]:
# Example 1 - working
arr11 = np.array([1, 2, 8, 2, 4, 3, 6, 4])

np.unique(arr11)

array([1, 2, 3, 4, 6, 8])

In [ ]:
# Example 2 - working
arr12 = np.array([["d","e","e"],
                  ["a","b","a"]])

np.unique(arr12)

array(['a', 'b', 'd', 'e'], dtype='<U1')

The function also works with String arrays.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr11 = np.append(arr11,None)

np.unique(arr11)

TypeError: ignored

Here, the error occurs because our array contains a None value. The unique function does not accept the None Value although it's a datatype in Python. It can be treated as

In [ ]:
arr11 = arr11[arr11 != None]

np.unique(arr11)

array([1, 2, 3, 4, 6, 8], dtype=object)

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'

## **Conclusion**

These are the 5 Simple Yet Interesting Numpy functions.
Thanks for Reading! :)

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/madhanmanoj1999/numpy-array-operations


'https://jovian.ai/madhanmanoj1999/numpy-array-operations'